### ISSUE TITLE
Title bar and borders in i3

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#103]
I found my application launched without title bar and borders in i3, where other apps have.

![2024-05-07_08-57](https://github.com/scorninpc/php-gtk3/assets/108541346/804c7188-982f-421b-a27e-732eac93d09e)

is any way to init GTK 3 app with this feature enabled?

**Comment by scorninpc** [comment]
Hello @d47081 

Can you provide a example code? 

What is "i3"?

This is not a Gtk feature, this is a window manager feature. If you want remove bars and borders, you need to tell Gtk to pass to WM, to not render bars and borders. You dont need to change anything to render that

provide your code, I can help more

**Comment by scorninpc** [comment]
What do you mean i3 ? i just know intel i3 processor :P
