### ISSUE TITLE
Use environment PHP version in EXTENSION_DIR by default? 

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#108]
Why not to keep system PHP version [in docs example](https://github.com/scorninpc/php-gtk3/blob/master/docs/compile-linux.md) and replace following command 

```
EXTENSION_DIR       =   $(shell /opt/php/php-8.1.14/bin/php-config --extension-dir)
```

with environment version

```
EXTENSION_DIR       =   $(shell /usr/bin/env php-config --extension-dir)
```

or that's not good idea?

same for PHP-CPP.

I mean documentation just, to simplify build steps there. Because not always useful to compile PHP from sources, and configure --options there not includes important components comparing to the native binaries.

**Comment by scorninpc** [comment]
it't not good idea. you can break your system if you use php with apache ou nginx
