### ISSUE TITLE
Gtk4 dependency warning

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#116]
I have strange notice from PHP-GTK3 app :)
for some reasons it call GTK-4 components installed for another app written on Rust.

How is it possible?

```
F: Can't get document portal mount path
Authorization required, but no authorization protocol specified

thread 'main' panicked at src/main.rs:74:17:
called `Result::unwrap()` on an `Err` value: BoolError { message: "Failed to initialize GTK", filename: "/run/build/Geopard/vendor/gtk4/src/rt.rs", function: "gtk4::rt::init", line: 158 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrac
```

Tried to reinstall `libgtk-3-dev libgladeui-dev libgtksourceview-3.0-dev libwnck-dev` but no success.

I don't remember how did installed GTK 4, maybe with cargo.. but strange to see that relation for PHP-GTK3

**Comment by scorninpc** [comment]
I never cannot understand your issues, you need to try to provide more details

Are you using appimage? you have compiled source? what php core are trigging this error?

Not make any sense call gtk4 files :(

**Comment by scorninpc** [comment]
i'm very interesting in this issue. I add some templates now, and if you complete than, this ill help alot

This issue occur on some action? or just to run a simple example?
What linux disto?
What linux distro version?
Did you compiled or using a appimage?
