### ISSUE TITLE
How to work with GtkFileChooserDialog

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#119]
Trying to create new object according to it's constructor:

``` php
$dialog = new \GtkFileChooserDialog(
    'test',
    new \GtkWindow
);
```
and get error

``` bash
/usr/bin/php-gtk3: line 2:  6814 Segmentation fault      /opt/php/php-8.3.9/bin/php -dextension=php-gtk3.so $@
```

Is any example how to create dialog with PHP properly?

Thanks

**Comment by scorninpc** [comment]
Look if this can help 

https://andor.com.br/php-gtk/cook/open-a-file-chooser-with-gtkfilechooserdialog
