### ISSUE TITLE
Gdk event constants

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#123]
Thoughts to implement some constants like `Gdk.EventType.DOUBLE_BUTTON_PRESS`

I'm currently using static numbers in my app:

``` php
$this->gtk->connect(
    'button-press-event',
    function (
        ?\GtkNotebook $self,
        ?\GdkEvent $event
    ) {
        // Close tab on double click
        if ($event->type == 5) // Gdk.EventType.DOUBLE_BUTTON_PRESS
        {
            $this->close();
        }
    }
);
```

Where is better to define GDK constants in PHP-GTK3?

By the way, here is related PR https://github.com/scorninpc/php-gtk3/pull/110
I'm still waiting for merge to continue

**Comment by scorninpc** [comment]
https://github.com/scorninpc/php-gtk3/blob/master/main.cpp#L403
