### ISSUE TITLE
Widget::has_focus return integer

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#128]
`Widget::has_focus` return integer not boolean type
https://docs.gtk.org/gtk3/method.Widget.has_focus.html

**Comment by scorninpc** [comment]
I need working code for that

My code returning boolean too https://github.com/scorninpc/php-gtk3/blob/1f24ea63a15b3f392a850f280d84573b19409582/src/Gtk/GtkWidget.cpp#L1983

**Comment by scorninpc** [comment]
This is a nice example about i'm talking about [d47081](https://github.com/d47081)

I wrote a code to test your problem, you understand?

```php
<?php

Gtk::init();

$win = new GtkWindow();
$win->set_default_size(300, 200);
$win->connect("destroy", "GtkWindowDestroy");

$button = \GtkButton::new_with_label("OK");
$win->add($button);
$button->connect("clicked", function($button) use ($win) {
	echo "OK\n";

	var_dump($win->has_focus());
	var_dump($button->has_focus());
});

$win->show_all();

Gtk::main();
```

and just after that i can confirm your problem
