### ISSUE TITLE
undefined symbol: gtk_init

### ISSUE THREAD

**Issue by eaguilar-dibal** [scorninpc/php-gtk3#13]
Hi, 

i'm trying to make run your program, and it not work.

After compile PHP-CPP and make in test examples, cli return me this message: 
"php: symbol lookup error: ./php-gtk3.so: undefined symbol: gtk_init"

My SO is Ubuntu 18.04.2

Can u help my, please? Thnks

**Comment by scorninpc** [comment]
Hello

Maybe you have wrong GTK version. Try see it with

```
$ dpkg -l libgtk2.0-0 libgtk-3-0
ii  libgtk-3-0:amd64  3.24.5-1     amd64        GTK+ graphical user interface library
```
Gtk 3.20 is minimum for run. 

Anyway, this appear to be a link error between php-gtk.so and Gtk libs.

Try run the .appimage on release page, if the problem are the same, you need update your system

Let's me know

**Comment by eaguilar-dibal** [comment]
This is the output of the dpkg command and the AppImage doesn't do anything:

![image](https://user-images.githubusercontent.com/54887582/64320475-ebe68600-cfbe-11e9-8e61-144f487bbe1e.png)

**Comment by scorninpc** [comment]
You need to pass some parameter, like you pass for php. -m, -v, the php file, etc

You can run -h to see all php parameters

![image](https://user-images.githubusercontent.com/2607849/64337777-6b238c00-cfb6-11e9-8c36-c00b5f7189c8.png)
