### ISSUE TITLE
markup_escape_text

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#130]
Seems this method wanted to escape data for `Label::set_markup` properly
https://docs.gtk.org/glib/func.markup_escape_text.html

I had used PHP function `htmlspecialchars` but 
```
(php:76903): Gtk-WARNING **: 04:44:57.040: Failed to set text
...
```

Example text too long, but supporse it could be any char of these:

``` php
<?php

Gtk::init();

$label = new \GtkLabel;

$label->set_use_markup(true);

$label->set_markup("🌧️ 🐞🐙");
```

**Comment by scorninpc** [comment]
You think i can escape by default ?

**Comment by scorninpc** [comment]
i got , but you think i can escape everytime with `g_markup_escape_text` or expose the method to espace if you want?

**Comment by scorninpc** [comment]
Your code works fine here

![image](https://github.com/user-attachments/assets/c038afc7-000b-4b2d-a19d-dbda8eace191)

You need show what?

I think `g_markup_escape_text` will escape tags. For example, if you need to show `<test>` in your text

**Comment by scorninpc** [comment]
I think you dont complete understand escape methods, encodes, etc

this all is a pattern to manipulate strings. methods and languages are irrelevants

in this case, php has advances to use iconv and mb_string

you can convert any encoded string to utf8 with `iconv(mb_detect_encoding($text, mb_detect_order(), true), "UTF-8", $text);` for example

**Comment by scorninpc** [comment]
anyway, if you want to implemente, go aread
