### ISSUE TITLE
Pango LayoutLine struct

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#131]
I'm working on the new features and stuck with following struct:
https://docs.gtk.org/Pango/struct.LayoutLine.html

Where I must to define it - beside other classes at this folder?
https://github.com/scorninpc/php-gtk3/tree/master/src/Pango

**Comment by scorninpc** [comment]
For sure, this is the class `PangoLayoutLine`, so inside Pango folder

![image](https://github.com/user-attachments/assets/3cb4f12d-1f0c-4d68-8013-b32953722122)

Gtk is increasingly decoupling these primitive classes and functions. I didn't plan on converting this type of classes. But it's ok

**Comment by scorninpc** [comment]
Wait, you need to see if this struct are usable

Sometimes, this is converted as a simple array on PHP

like 

```php
$a = [
'layout' =>$layout,
'length' =>13,
'runs' => [],
'isparagraph_start' => 1
];
```

like gtktreepath https://github.com/scorninpc/php-gtk3/blob/5992f0119902998a50b7d3ab96c42758092cd48b/src/Gtk/GtkTreeView.cpp#L309
