### ISSUE TITLE
Question about php-config in Makefile

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#136]
I'm using few `php-gtk3` builds, and found that one of them does not work after build

```
Fatal error: Uncaught Error: Class "Gtk" not found
```

Suppose that because makefile linked to global `php-config` here:

https://github.com/scorninpc/php-gtk3/blob/master/Makefile#L110

I'm trying to add absolute (local version) path but it not works (maybe because of quotes, don't know)

Can be the reason?

Maybe it's better to add global variable like this one?
https://github.com/CopernicaMarketingSoftware/PHP-CPP/blob/master/Makefile#L20

**Comment by scorninpc** [comment]
i dont see corelacionation between php-config and not load of extension @d47081 

php-config are just used to install extension and headers

are you compiling with one version of php and running with another one?

**Comment by scorninpc** [comment]
`INI_DIR` is only used to install

https://github.com/scorninpc/php-gtk3/blob/master/Makefile#L157

if you dont show me all the output, I really cannot help. If everyone can compile and run, it's work and you have or missing something, that I can just help if you help me to understant

**Comment by scorninpc** [comment]
I just can tell you, with this comment

> php -dextension=php-gtk3.so app.php - OK
> /path/to/local/php -dextension=php-gtk3.so app.php - Gtk class not found

is that you are compilling php-gtk with global php, and not with `/path/to/local/php`, and, if you run  `/path/to/local/php -dextension=php-gtk3.so app.php` the error maybe are "cannot load shared extension"

if is that case, you need to see the complete error to try solve, or compile to `/path/to/local/php`, not to global default php

**Comment by scorninpc** [comment]
@d47081 i really need to see all complete message output?

like this:

![image](https://github.com/user-attachments/assets/f1a41fd9-b760-4a1a-842b-b4542e4c5aa2)

I need to see command, i need to see full output


and please, provide output of `-m `, like this

![image](https://github.com/user-attachments/assets/417ff7a8-08aa-443b-9a7c-3490904955c4)

**Comment by scorninpc** [comment]
you still not sending me all, command and output

here you define php-config, but it's used only to see path to install, just it

php-gtk3 does not need php headers, its use php-cpp only

![image](https://github.com/user-attachments/assets/482578dc-4dec-4b27-bb15-da7dda30df6a)

**Comment by scorninpc** [comment]
You are installing `PHP-CPP` in a custom directory, https://github.com/YGGverse/Yoda/blob/main/INSTALL.sh#L15 without adding this to `LD_LIBRARY_PATH`, so when you compile PHP-GTK3, compiller will use `/usr/lib` one, not the compiled one

**Comment by scorninpc** [comment]
You can see search path priority. Compiler will use the first found

I can't help much, this is obviously a system/environment problem, but I believe this is the way to go
