### ISSUE TITLE
How to debug with php-gtk?

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#139]
e.g.
``` bash
GTK_DEBUG=interactive ./your_gtk_application
```

I want to dump class names used for `GtkCssProvider`

**Comment by scorninpc** [comment]
This?

https://github.com/scorninpc/php-gtk3/blob/master/src/Gtk/GtkWindow.cpp#L949

https://docs.gtk.org/gtk3/type_func.Window.set_interactive_debugging.html
