### ISSUE TITLE
How to define application title in dock menu

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#140]
I found the application launched with php-gtk has title `Php` on mouse hover (because of call php maybe)

Is it possible to change/customize it?
Unfortunately can't grab the screenshot on application icon hover but it should be same everywhere.

p.s. I have following desktop launcher:

```
[Desktop Entry]
    Name=Appname
    Comment=Some description
    Type=Application
    Exec="/path/to/launcher.sh"
```

where launcher contain

```
#!/bin/bash
"/path/to/php" -dextension="php-gtk3.so" "/path/to/app/src/app.php" $@
```

**Comment by scorninpc** [comment]
Sorry, but this is not php-gtk related problem. I really dont know what docker is it, what window manager is it, nothing dude!

i think this kind of question can be done on facebook group, there is a little people, but more than I

https://www.facebook.com/groups/6986199624801916
