### ISSUE TITLE
PangoLayout_::xy_to_index implementation

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#143]
**GTK documentation**
https://docs.gtk.org/Pango/method.Layout.xy_to_index.html

I have following draft:

``` cpp 
Php::Value PangoLayout_::xy_to_index(Php::Parameters &parameters)
{
	gint x = (gint) parameters[0];
	gint y = (gint) parameters[1];

	gint* index_;
	gint* trailing;

	return pango_layout_xy_to_index(PANGO_LAYOUT(instance), x, y, index_, trailing);
}
```

This implementation process `x` and `y` arguments properly, but:

1. how to return `index_` and `trailing` values generated as php parameters?
2. should I use `int` or `gint` there?
3. this method return to php integer 0|1 not boolean as documented, how to make canonical boolean type return?

---
btw, app code fragment for tests where I'm trying to get link address on middle button click by this feature

``` php
$this->gtk->connect(
    'button-press-event',
    function(
        GtkLabel $label,
        GdkEvent $event
    ) {

        if ($event->button->button == 2) // @TODO Gdk::BUTTON_MIDDLE #141
        {
            $index = null;
            $trailing = null;

            $result = $label->get_layout()->xy_to_index(
                $event->button->x * Pango::SCALE,
                $event->button->y * Pango::SCALE,
                $index,
                $trailing
            );

            var_dump($result);
            var_dump($index);
            var_dump($trailing);

            // next operations with index received ...

        }

        return true;
    }
);
```

**Comment by scorninpc** [comment]
1. you can return array with 2 indexs: `index`and `trailing`
2. if `pango_layout_xy_to_index` use int, so you need to use int too. but, gint is a int alias
3. i think you can return the array if OK, and false if error

**Comment by scorninpc** [comment]
> is it okay that function API will be changed of that? maybe you too don't know how to make it as linked argument back or that's just impossible with php-cpp

this is a pattern since php-gtk1, it's not ok use reference args with php
