### ISSUE TITLE
undefined symbol: gdk_pixbuf_get_type on wayland 

### ISSUE THREAD

**Issue by scorninpc** [scorninpc/php-gtk3#15]
Tested by @RobertBeran

Compiled nice, but error when run

`php: symbol lookup error: ./php-gtk3.so: undefined symbol: gdk_pixbuf_get_type`

**Comment by scorninpc** [comment]
Fixed eb35c3113214bffc4cc8df204632c68666c5f433

**Comment by subabrain** [comment]
Hi,

thanks a lot @scorninpc !!!

it works now with my ubuntu :)

Greets
Robert
