### ISSUE TITLE
g_object_unref or how to destroy objects created?

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#151]
I have [following code](https://github.com/YGGverse/Yoda/blob/main/src/Abstract/Model/Gtk/Pango/Markup.php#L142) to make custom word wrap width calculation using markup dimensions:

``` php
    // iterated
    public static function width(
        string $markup
    ): ?int
    {
        $layout = new PangoLayout(
            (new GtkDrawingArea)->create_pango_context()
        );

        $layout->set_markup(
            $markup, -1
        );

        if ($size = $layout->get_pixel_size())
        {
            return $size['width'];
        }

        return null;
    }
```
I'm worried, this static method may create lot of objects in memory and not sure php able to destroy them after use.

So, found `g_object_unref` function that able to destroy `PangoLayout` but seems this method not implemented yet.
I want to destroy `GtkDrawingArea` also, with php-gtk API and without destroy entire the app launched.

Is any ideas how to make it properly?

**Comment by scorninpc** [comment]
you dont need worrie!

first, g_object_unref will destroy undef gpointer, not php object. this method may need to implemented to use in another situations

and php can handle this https://www.php.net/manual/en/features.gc.php

**Comment by scorninpc** [comment]
are you facing some problem?

**Comment by scorninpc** [comment]
`g_object_unref`will not work for you. You are using pango https://docs.gtk.org/Pango/index.html?q=free

better not implement things that work with memory. just do it if you are facing problem
