### ISSUE TITLE
GtkWindow constructor

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#157]
https://docs.gtk.org/gtk3/ctor.Window.new.html

By the documentation, constructor must contain 
https://docs.gtk.org/gtk3/enum.WindowType.html

PHP access implemented in
https://github.com/scorninpc/php-gtk3/pull/156

If API has another implementation, it would be more correct to set on cpp side `GTK_WINDOW_TOPLEVEL` not `0`

**Comment by scorninpc** [comment]
> maybe that's no sense to change lib api for compatibility reasons

for real? hahahah

gtkwindow was one of the first methods that was programmed. This change would be great. It's a shame that you think so.
