### ISSUE TITLE
Error when loading glade file (add_from_file)

### ISSUE THREAD

**Issue by Nijhuis** [scorninpc/php-gtk3#168]
I am transitioning from PHP 5.x and GTK2 to PHP8.x and GTK3.

I am unsure if this is whitin the scope of this project, but when loading a glade file I get an error that I dont understand.

<?php

$this->wnd = new GtkBuilder();
$this->wnd->add_from_file("gladefile.glade");

gtk::main();

ERROR: (process:27516): Gtk-CRITICAL **: 13:35:13.984: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

**Comment by scorninpc** [comment]
Hey, hi

You need to see if this glade file works at GTK 3. Maybe do some tests with a clean glade file too

This is an internal error provided by glade parser, so its hard to find the main problem

Maybe i can help more if send me the glade file (you can send me on private if you want at scorninpc on google mail provider )

**Comment by Nijhuis** [comment]
Great, thanks for the tip. This worked. Will try and clean up my old glade files.
