### ISSUE TITLE
fatal error: gtk/gtk.h: No such file or directory when running make

### ISSUE THREAD

**Issue by nimbfire** [scorninpc/php-gtk3#20]
I'm not sure what I did wrong or what is missing. I've installed the libraries as instructed in the README. Also, I did found the gtk.h at /usr/include/gtk-3.0/gtk/gtk.h but the compiler does not seem to find it.

Oh, I'm using Ubuntu 19.10, not sure if its relevant

Não sei o que estou fazendo de errado. Eu instalei as bibliotecas como instruido no README. Ah, também encontrei o arquivo gtk.h na pasta /usr/include/gtk-3.0/gtk/gtk.h mas parece que o compilador (é o compilador mesmo?) não encontra ele. Cheguei a tentar criar um link simbolico "gtk -> /usr/include/gtk-3.0/gtk/gtk.h" mas também não funcionou.

Ah, e estou usando o Ubuntu 19.10, não sei se é relevante.

```
php-gtk3-tests git:(master) ✗ make
g++ `pkg-config --cflags gtk+-3.0 gladeui-2.0 gtksourceview-3.0 gtk-mac-integration-gtk3` -Wall -Wno-inconsistent-missing-override -c -std=c++11 -fpic -o  src/G/GApplication.o src/G/GApplication.cpp 
Package gtk-mac-integration-gtk3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk-mac-integration-gtk3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk-mac-integration-gtk3' found
In file included from src/G/GApplication.cpp:2:
src/G/GApplication.h:6:14: fatal error: gtk/gtk.h: No such file or directory
    6 |     #include <gtk/gtk.h>
      |              ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:125: src/G/GApplication.o] Error 1

```

**Comment by scorninpc** [comment]
You can run ```dpkg -l libgtk2.0-0 libgtk-3-0``` to see installed version

You can run ```pkg-config --cflags gtk+-3.0 gladeui-2.0 gtksourceview-3.0``` to see if compiler are getting dependencies ok

Some distros need to relog to remake path, some others need completly reload

Anyway, you can run .image from release. Just make it executable and run like the php executable

**Comment by subabrain** [comment]
The Problem is, that this file/path is not in your standard include directory - i had the same error with a fresh ubuntu (and other distributions) ... just search for the header Files in your standard include folder - something like: /usr/include/ - then copy them on the right place if required from the compiler ... so if you have a new ubuntu build - you have to do this first :)

**Comment by scorninpc** [comment]
I know that's old, the time pass like a boss

But i fix the problem on linux compiler. It's because he looking for lib gtk osx integration. Now it's fixed

#ccf8e6c
