### ISSUE TITLE
phpcpp and php-gtk3 with mingw

### ISSUE THREAD

**Issue by subabrain** [scorninpc/php-gtk3#21]
Hello together,

i have a problem when compiling phpgtk3 with mingw from debian - the code of phpgtk3 works to compile but if its compiling the phpcpp lib there are some strange errors:

/usr/i686-w64-mingw32/include/phpcpp/inivalue.h:17:21: error: variable ‘Php::PHPCPP_EXPORT Php::IniValue’ has initializer but incomplete type
 class PHPCPP_EXPORT IniValue

... and so on ....

Does somebody know whats this Problem?

Greets
Robert

**Comment by subabrain** [comment]
Ok i think its not a Problem with phpgtk3 more than a Problem with MinGW and PHP-CPP ...

**Comment by scorninpc** [comment]
Any php extensions with MinGW is a problem. If you compile PHP-CPP you can compile PHP-GTK3

**Comment by subabrain** [comment]
okay - today i will try again to compile with windows :)

**Comment by scorninpc** [comment]
Nice!

But i'm working on a generated code, non dependency, new code

https://github.com/scorninpc/php-gtk4

With this we'll compile natively on windows, without dependencies, and will support gtk 3 and gtk 4. So i'm unmaintenancing this repo (php-gtk3) for now

**Comment by subabrain** [comment]
ah ok - great :)

tried now ... but i got it working with linux but its a bit hard to get it with the mingw compiler under debian ...

greets

**Comment by scorninpc** [comment]
mingw is a problem as I said. You will not get this work with mingw

https://stackoverflow.com/questions/3711327/how-do-you-compile-a-php-extension-on-windows-with-cygwin-mingw

You really need VS to compile PHP-CPP on windows, and then compile PHP-GTK easy

**Comment by subabrain** [comment]
hello

okay - ill try this :)

**Comment by subabrain** [comment]
Hi there,

i think its easier than expected. Just had to modify the makefile to create .dll files - but i just have to test ...

Greets
Robert

**Comment by subabrain** [comment]
hi boys and girls,

i finaly get php-cpp compile under cygwin ... with cmake ... and now i want to integrate it in the llibs ...

please help me :)

thanks a lot!
Robert

**Comment by scorninpc** [comment]
Nice to know @subabrain. What do you want now? just add php-gtk lib on cmake list of libs and do the compile to see the errors of the lib now. Post it and i will try to reproduce. Or if you want, make a "HOW TO", to others try compile it too

**Comment by subabrain** [comment]
Hi,

okay - i thought it was wrong - just get the phpcpp-common .dll file but not the real phpcpp project...

so i get phpcpp it in an .a file (that works) ... i try now to compile it from cmake / visual studio ... but i think there are some code errors -> maybe im wrong - but i believe that here is c/c++ mixed in one file ...

i will try further ...

Greets
Robert

**Comment by subabrain** [comment]
Hi,

okay - i got now the phpcpp-common.lib compiled -> with visual studio. 
Do i have to load this .lib for compiling the main phpcpp?

would be nice if you could answer ....

Greets
Robert

**Comment by scorninpc** [comment]
You need the phpcpp.dll to compile php-gtk

**Comment by scorninpc** [comment]
Oh Robert, I would really like to help, but I don't know anything about windows

**Comment by subabrain** [comment]
Okay,

i have the .dll of phpcpp now .... now just compile phpgtk3 :)

Greets
Robert

**Comment by scorninpc** [comment]
Nice, you can share the dll?

**Comment by subabrain** [comment]
Hi,

sorry the .dll is corrupt :(

i try to make a mingw 32 bit version - i hope it will be working :)

Greets
Robert

**Comment by subabrain** [comment]
okay,

i think its ok now - but one missing .dll:

![2022-01-03 00_00_55-Dependencies (x64)](https://user-images.githubusercontent.com/7425736/147891724-cffdc2f6-305d-44ac-a9af-275e3af51b85.png)

maybe someone could help :)

GN8!

**Comment by scorninpc** [comment]
I would really like to be helping you, but for over 10 years I haven't opened a windows. the last version I saw was NT

**Comment by subabrain** [comment]
😄

**Comment by subabrain** [comment]
Ok,

if somebody can speak German - this is the link to my describtion how make dlls under Ubuntu:

https://burncycle.de/2022/01/06/dll-von-cpp-datei-unter-linux-erstellen/

Greets
Robert

**Comment by scorninpc** [comment]
@subabrain, and if we create a docker? it can be run on mac and windows without problems

**Comment by subabrain** [comment]
hmm - i dont think so ..... i try it once again today evenening .... if it not works i will do it maybe a docker ...

Greets
Robert

**Comment by subabrain** [comment]
hi,

sorry for the long delay -> i will compile php-cpp with cmake for windows and then i compile with visual studio php-gtk3 :)

Greets
Robert

**Comment by subabrain** [comment]
ok,

i got the lib now for windows from phpcpp :)

now itry to compile phpgtk 3 with viusal studio :)

Greets
Robert

**Comment by scorninpc** [comment]
Better work and documentation on issue #24
