### ISSUE TITLE
libwnck/libwnck.h: No such file or directory

### ISSUE THREAD

**Issue by davekimble2** [scorninpc/php-gtk3#22]
This is my first attempt to get PHP-GTK3 running on Ubuntu_20.04.
It uses PHP-CPP from Copernica.

Install the building tools:
sudo apt-get install build-essential gnome-devel php-dev libgladeui-dev libgtksourceview-3.0-dev

Get PHP-CPP and build it:
git clone https://github.com/CopernicaMarketingSoftware/PHP-CPP.git
cd ./PHP-CPP
make
sudo make install

Get test files and build them:
git clone https://github.com/scorninpc/php-gtk3-tests.git
cd php-gtk3-tests
make
    ...
    In file included from src/libwnck/WnckScreen.cpp:2:
    src/libwnck/WnckScreen.h:6:11: fatal error: libwnck/libwnck.h: No such file or directory
        6 |  #include <libwnck/libwnck.h>
             |           ^~~~~~~~~~~~~~~~~~~
    compilation terminated.
    make: *** [Makefile:154: src/libwnck/WnckScreen.o] Error 1
    
The file ./PHP-CPP/php-gtk3-tests/src/libwnck/libwnck.h does indeed not exist.

**Comment by scorninpc** [comment]
As error show, you need libwnck

You can download with:

`apt-get install libwnck-dev`

Or you can get appimage from releases page

**Comment by fanyufan** [comment]
How about install libwnck on mac? I use this `sudo port install libwnck`, but still have the issue.

**Comment by scorninpc** [comment]
Using port, you need to add the path of libwnck manualy, but sorry, i dont have mac for test

**Comment by fanyufan** [comment]
> Using port, you need to add the path of libwnck manualy, but sorry, i dont have mac to test

Thanks. you are right. 

BTW, I find another issue. Is it something wrong in the source code?

$ make WITH_LIBWNCK=1

g++ `pkg-config --cflags gtk+-3.0 gladeui-2.0 gtksourceview-3.0  libwnck-3.0` -DWITH_LIBWNCK -DWNCK_I_KNOW_THIS_IS_UNSTABLE -I/opt/local/include/libwnck-3.0 -Wall -Wno-inconsistent-missing-override -c -std=c++11 -fpic -o  src/libwnck/WnckScreen.o src/libwnck/WnckScreen.cpp
src/libwnck/WnckScreen.cpp:40:10: error: conversion from 'long' to 'Php::Value' is ambiguous
                return NULL;
                       ^~~~

**Comment by scorninpc** [comment]
Sorry, I really dont know about new macs, but i'm sure the code works on previos mac and php version. do you do this changes https://github.com/scorninpc/php-gtk3/blob/master/mac-compile.md?
