### ISSUE TITLE
php-gtk3 for windows

### ISSUE THREAD

**Issue by subabrain** [scorninpc/php-gtk3#24]
Hey there,

i got to compile phpcpp as a .lib / .dll file for windows.

here a link to the solution:

https://github.com/CopernicaMarketingSoftware/PHP-CPP/issues/443

i am trying to compile php-gtk3 now with visual studio and phpcpp ..

But it is not very easy :/

Maybe someone could help - thanks a lot!

Greets
Robert

**Comment by scorninpc** [comment]
Hey Robert.

You are doing a lot nice work, thank you

What the problem or error? i dont have any windows machine that can i install and help, but i can try help if you show some erros and processes

Thank you

**Comment by subabrain** [comment]
Hi,

i dont have problems with the libraries (i get them from vcpkg) - but with compiling errors ... i also tried to add the header files from glib/gtk/gdk and so on ... i will post the exact errors here later ...

Greets
Robert

**Comment by subabrain** [comment]
ok here,

in c its:

![c](https://user-images.githubusercontent.com/7425736/201387538-445b538e-5a01-40ef-9601-fc4793bba353.png)

and in c++:

![c++](https://user-images.githubusercontent.com/7425736/201387573-3b08b557-c46c-43a0-b414-ab212cfd38f4.png)

- so if i take c there is no static function and in c++ there are no types ...

please help here :)

Greets
Robert

**Comment by scorninpc** [comment]
why c++ has no types? everything is c++

C has no classes, so C is out of possible

I'm compiling with standard 11. this can be the problem? i think visual studio has 17 as default, if i'm not wrong 

Try to add `-std=c++11` as parameter in g++ compiler

**Comment by subabrain** [comment]
hi,

i think you misunderstood - i get this errors when compiling with the c / c++ language ...

but i will try one thing - i will report here ....

Greets
Robert

**Comment by subabrain** [comment]
hi,

you cant compile gtk with g++ - you must compile as c

![grafik](https://user-images.githubusercontent.com/7425736/201515761-be3278ae-c763-43f5-87f2-fdff4fbf30bb.png)

here is the c++ workaround:

https://www.gtk.org/docs/language-bindings/cpp

please help here!

Greets
Robert

**Comment by subabrain** [comment]
Hi there,

ok - i think i figured out ... it has to do with the glib dependencies ...

maybe someone could help / explain me what to do?

Greets
Robert

**Comment by scorninpc** [comment]
The better way to try, maybe be do some simple projects with GTK, without PHP, to know dependencies of GTK on windows. After you compile a simple hello world with GTK, you know dependencies, and can add this to PHP-GTK

**Comment by subabrain** [comment]
Hi,

okay - its a good way :)

i will try later :)

Greets
Robert

**Comment by subabrain** [comment]
Hi,

ok, im very far now ... maybe one question:

where is the type "GType" defined?

i searched but its not working .... with the:

#include "glib/gtypes.h"
#include "glib/glib.h"
#include "glib/glib-object.h"
#include "gobject/gtype.h"
#include "gobject/gobject.h"
#include "glib/glib-object.h"

Greets
Robert

**Comment by scorninpc** [comment]
Where did you use GType?

https://github.com/GNOME/glib/blob/1d7dfb68e8e31ad0f1d682626b7a37ff9a7dc512/gobject/gtype.h

**Comment by subabrain** [comment]
here

![image](https://user-images.githubusercontent.com/7425736/203323807-25056cac-4c56-47f7-b9bd-3d56ce59f751.png)

Greets
Robert

**Comment by scorninpc** [comment]
ah ok

This is defined on gtk.h , that include gobject.h, that include gtype.h

**Comment by subabrain** [comment]
hi,

okay - i fixed now the gtype stuff :)

![image](https://user-images.githubusercontent.com/7425736/203759143-5c39b4d4-2682-4f66-b679-31fe14932805.png)

Greets
Robert

**Comment by subabrain** [comment]
hi,

okay - i think i got it now ... just compile it like this:

https://www.collabora.com/news-and-blog/blog/2021/03/18/build-and-run-gtk-4-applications-with-visual-studio/

then just add the .dll of phpcpp to your project and then compile with visual studio :)

Greets
Robert

**Comment by subabrain** [comment]
hi,

for all others - the problem was the glib dependencies in visual studio ... i used vcpkg for that :)

Greets
Robert

**Comment by subabrain** [comment]
Now just put the parts together for phpgtk 📦

Greets
Robert

**Comment by subabrain** [comment]
ok -i got to compile but im linking at the moment :P 

Greets
Robert

**Comment by subabrain** [comment]
ok - i will post today evening the .dll ... and an explanation how to compile with visual studio :)

Greets
Robert

**Comment by scorninpc** [comment]
thats run a simple gtkwindow?  =D veeeery nive

**Comment by subabrain** [comment]
> thats run a simple gtkwindow? =D veeeery nice

what you mean exactly?

Greets
Robert

**Comment by scorninpc** [comment]
> ok - i will post today evening the .dll ... and an explanation how to compile with visual studio :)

did you compiled and run any php-gtk test? its working?

**Comment by subabrain** [comment]
> > ok - i will post today evening the .dll ... and an explanation how to compile with visual studio :)
> 
> did you compiled and run any php-gtk test? its working?

hi, sorry the version for 64 bit is not working :/ 

sorry for that but i am working on the 32 bit version ....

Greets
Robert

**Comment by subabrain** [comment]
hi,

ok - i got it but i dont see any window :P - tell me please if this is maybe because of the php version?

i took php 7.4.0?

Greets
Robert

**Comment by scorninpc** [comment]
i need to see your php code to tell something to you

when you run `php -m` gtk is on the list?

**Comment by subabrain** [comment]
here:

![grafik](https://user-images.githubusercontent.com/7425736/208545247-f4b13472-f5d5-4361-9f85-762989c9502c.png)

i will post tomorrow ...

Greets
Robert

**Comment by scorninpc** [comment]
Nice, you done it

Now you can run

```php
<?php

Gtk::init();

function GtkWindowDestroy($widget=NULL, $event=NULL)
{
	Gtk::main_quit();
}

$win = new GtkWindow();
$win->set_default_size(300, 200);
$win->connect("destroy", "GtkWindowDestroy");
$win->show_all();
```

this need to open a blank window

![image](https://user-images.githubusercontent.com/2607849/208679883-1eb4fac8-ac18-4027-b32f-34e0a42fe4f4.png)

**Comment by subabrain** [comment]
okkkkk,

it works :))))))))))

![grafik](https://user-images.githubusercontent.com/7425736/208724184-772d1414-ec81-4c84-b90f-17847277529f.png)

that was hard :/

Greets
Robert

**Comment by scorninpc** [comment]
I dont believe hahahha thats the news of year!

Can you provide some zip, like a portable of this? with php and the php-gtk3.dll?

**Comment by subabrain** [comment]
hi,

yes i will do now :)

Greets
Robert

**Comment by subabrain** [comment]
Hi,

ok here the ready version of php-gtk3 for windows -> its 64 bit based on php 7.3.0 :)

https://1drv.ms/u/s!AifVi84AXOwIhZRvuxxvmrOXbowYjw?e=Y19a8W

Please Test and give Response -> please notice -> you have to install the required redists ...

Greets
Robert

**Comment by scorninpc** [comment]
Very nice! i'll create a VM this weekend to test this. If you provide the steps to compile, i'll update documentation and try compile too

**Comment by subabrain** [comment]
Hi Bruno,

ok .. i will do it later ;)

Greets
Robert

**Comment by subabrain** [comment]
Hi,

can i make a repository for phpgtk3 (windows) with visual studio here at github?

thanks a lot!

Greets
Robert

**Comment by scorninpc** [comment]
i think we need use the same, for the updates

fork and do a PR with your changes

**Comment by subabrain** [comment]
hi,

ok - i see - we will do :)

Greets
Robert

**Comment by subabrain** [comment]
Ok here,

a little Tutorial about Compiling PHP-GTK3 for Windows with Visual Studio :)

Please give Response :)

[Compile.docx](https://github.com/scorninpc/php-gtk3/files/10295638/Compile.docx)

Greets
Robert

**Comment by scorninpc** [comment]
Robert, you do a nice work

I'll translate it to [here](https://github.com/scorninpc/php-gtk3/blob/master/docs/compile-windows.md) ok?

**Comment by subabrain** [comment]
> Robert, you do a nice work
> 
> I'll translate it to [here](https://github.com/scorninpc/php-gtk3/blob/master/docs/compile-windows.md) ok?

its ok ;)

Greets
Robert

**Comment by scorninpc** [comment]
This a lot work hahaha https://github.com/scorninpc/php-gtk3/blob/master/docs/compile-windows.md

Now i'll make a Windows VM to test your .zip file

**Comment by subabrain** [comment]
Ok,

good luck! - please dont forget to install the redists ...

Greets
Robert

**Comment by scorninpc** [comment]
I'm totaly noob on windows
![image](https://user-images.githubusercontent.com/2607849/209416796-6760446d-5fec-4036-93ed-d97cd741883e.png)

**Comment by subabrain** [comment]
Hi,

i think its because of the redists - i think you have to install also the old ones - i will test - give me some hours :)

Greets
Robert

**Comment by subabrain** [comment]
Ok,

i think it is because of the .net framework - i will have a look at a fresh virtual installation ... please give me some time ;)

Greets
Robert

**Comment by subabrain** [comment]
Hi,

okay - please try this one:

https://1drv.ms/u/s!AifVi84AXOwIhZR28F7EKuSOFAsuFg?e=uiPT5S

Thanks!

Merry Christmas!
Robert

**Comment by scorninpc** [comment]
> okay - please try this one:
> 
> https://1drv.ms/u/s!AifVi84AXOwIhZR28F7EKuSOFAsuFg?e=uiPT5S

Yes, it's working

![Capturar_select-area_20221226112716](https://user-images.githubusercontent.com/2607849/209559144-0756e569-cfd7-4f6f-921a-42bd6ee04fa0.png)


![Capturar_select-area_20221226112856](https://user-images.githubusercontent.com/2607849/209559163-b17e25ff-4c37-4205-ac82-8a2a5a43cabf.png)


> You must copy these files from the msys "bin" folder to your PHP binary root folder:

Ok, i've updated the documentation

I found a little problem with pixbuf icons and images

![Capturar_select-area_20221226112922](https://user-images.githubusercontent.com/2607849/209559179-a9fa76f9-4951-4d16-bd0c-f7be89330794.png)

I think the problem 1 are that cannot find stock icons. Try to run this [example](https://github.com/scorninpc/php-gtk3/blob/master/examples/test2.php)

The second problem, i dont know why, PHP cannot find my image

![image](https://user-images.githubusercontent.com/2607849/209560674-0ef312e2-d76f-4cb7-b246-a70e2bae57b4.png)

This is the example i'm running

```php
<?php

Gtk::init();

function GtkWindowDestroy($widget=NULL, $event=NULL)
{
	Gtk::main_quit();
}

echo "\n\n";
echo getcwd() . "\n";
echo "\n\n";
echo system('dir') . "\n";
echo "\n\n";

$win = new GtkWindow();
$win->set_default_size(300, 200);
$win->connect("destroy", "GtkWindowDestroy");

$img = GtkImage::new_from_file("C:\\Users\\admin\\Desktop\\examples\\twitter.png");

$btn = new GtkButton("Tw");
$btn->set_image($img);

$win->add($btn);
$win->show_all();


Gtk::main();
```

Anyway, you dont know how i'm happy to run a example on windows hahahah

**Comment by subabrain** [comment]
Hi,

ok i see ... i will have a look!

Greets
Robert

**Comment by scorninpc** [comment]
I think that are 2 problems

1 - I dont know why it cannot find my image
2 - When it not find my image, they try to add a broken image icon, so the icons of pixbuf are not on zip package

For the first one, i really dont understand. I've done all tests I can, but no success

For second, maybe add the icons anywhere and add it to path, maybe works. I'll do a installer after package are OK, so dont worry with that "manual action" ok?

**Comment by scorninpc** [comment]
I solved creating the cache with `gdk-pixbuf-query-loaders --update-cache` and copy `c:\msys64\mingw64\lib\gdk-pixbuf-2.0` to `PHP_DIR/lib/`

![image](https://user-images.githubusercontent.com/2607849/209585710-bb518b88-5521-43c3-af44-46fb5110aabc.png)

This can be a right way?

**Comment by scorninpc** [comment]
Appear to works fine! From png, from jpeg and theme name

![image](https://user-images.githubusercontent.com/2607849/209586279-456acadc-d421-43b3-88e6-966d042ffed9.png)

**Comment by subabrain** [comment]
👍 👍 👍

**Comment by subabrain** [comment]
Hi,

ok - please add your adjustments to the Tutorial and please update - to put the file "glibconfig.h" from the folder "mingw64\lib\glib-2.0\include\" to the folder "mingw64\include\glib-2.0". And update the Preprocessor to:

```
%(PreprocessorDefinitions)
_WINDOWS
_WIN32
NDEBUG
ZEND_DEBUG=0
_CRT_SECURE_NO_WARNINGS
PHP_WIN32
ZEND_WIN32
_MSC_VER=1934
PHP_COMPILER_ID="VC15"
_CRT_NONSTDC_NO_DEPRECATE
_NOEXCEPT=noexcept
G_PLATFORM_WIN32
GIO_COMPILATION
BUILDING_PHPCPP
PHP_VERSION_ID=70300
GDK_PIXBUF_COMPILATION
GDK_COMPILATION
GTK_COMPILATION
GLIB_COMPILATION
```

Thanks a lot!

Greets
Robert

**Comment by subabrain** [comment]
Hello @all,

i saw, that there is a folder needed - the name is "share" and it is located in the root dir of php ... i packed now all together so this version should work for you :)

https://1drv.ms/u/s!AifVi84AXOwIhZR53jkm-y4JrCYkoA?e=HchNmt

Have Fun!

Notice: Please tell me if its working for you all 😃 

Greets
Robert

**Comment by scorninpc** [comment]
Works fine, but what version of GTK are you using? The icon theme are the correct version?

Look GtkSpinner for example. Its added to 3.24. The example works fine but without loading icon

![image](https://user-images.githubusercontent.com/2607849/209871669-e1172157-85e8-4aa9-912c-db3f7a1bd617.png)

With my Adwaita icon theme, its appear, look:

![image](https://user-images.githubusercontent.com/2607849/209871835-174a32c5-12ea-4b95-880b-1b48d020983a.png)

**Comment by scorninpc** [comment]
> to put the file "glibconfig.h" from the folder "mingw64\lib\glib-2.0\include" to the folder "mingw64\include\glib-2.0"

Where i can put this on the tutorial?  `GTK Dependencies` section?

**Comment by subabrain** [comment]
hi,

ok try this one:

https://1drv.ms/u/s!AifVi84AXOwIhZR7hxFQVXNOWa-WRA?e=2SXQt8 

Greets
Robert

**Comment by subabrain** [comment]
> > to put the file "glibconfig.h" from the folder "mingw64\lib\glib-2.0\include" to the folder "mingw64\include\glib-2.0"
> 
> Where i can put this on the tutorial? `GTK Dependencies` section?

yes just put it there as first point (GTK Dependencies) .... thx!

Greets
Robert

**Comment by scorninpc** [comment]
> ok try this one:

Appear to be ok 

![image](https://user-images.githubusercontent.com/2607849/209891832-7f375744-2b7e-4f11-a569-07cd2064cfd6.png)

> yes just put it there as first point (GTK Dependencies) .... thx!

Ok, updated

Can I add this build to be downloaded on release page?

Another question: its easy to try with PHP 8.1.14? maybe some PR of PHP-CPP needed to be [merged manually](https://github.com/CopernicaMarketingSoftware/PHP-CPP/pull/497), but you think its can be done? if its a problem for you, I'll try to follow the steps

**Comment by subabrain** [comment]
> > ok try this one:
> 
> Appear to be ok
> 
> ![image](https://user-images.githubusercontent.com/2607849/209891832-7f375744-2b7e-4f11-a569-07cd2064cfd6.png)
> 
> > yes just put it there as first point (GTK Dependencies) .... thx!
> 
> Ok, updated
> 
> Can I add this build to be downloaded on release page?
> 
> Another question: its easy to try with PHP 8.1.14? maybe some PR of PHP-CPP needed to be [merged manually](https://github.com/CopernicaMarketingSoftware/PHP-CPP/pull/497), but you think its can be done? if its a problem for you, I'll try to follow the steps

Hi,

yes of course you can add this build 👍 

yes its possible to do with PHP 8 - but you have to compile it new with the sources and binaries for PHP 8.

i will have a look :)

Greets
Robert

**Comment by scorninpc** [comment]
Nice Robert

So I think i'll close this issue, and open another for PHP 8.1 ok? Now we have a official windows package =)

Thank you alot

**Comment by subabrain** [comment]
> Nice Robert
> 
> So I think i'll close this issue, and open another for PHP 8.1 ok? Now we have a official windows package =)
> 
> Thank you alot

Hi,

yes of course ;)

Greets
Robert
