### ISSUE TITLE
SourceView not working / Example 5

### ISSUE THREAD

**Issue by apss-pohl** [scorninpc/php-gtk3#27]
Hi,
we just tried to get the sourceview running following your code example 5.
Unfortunately it doesn`t work, we get an empty input. Is there maybe a regression since that example was created?

Thank you

**Comment by scorninpc** [comment]
I suppose that you don't understand the example, or gtksourceview 

Maybe because the GtkSourceView doesn't have frame, but after the empty input (GtkEntry), there is a GtkSourceView

![image](https://user-images.githubusercontent.com/2607849/213239633-1d422b40-8bb5-416f-8d20-97cc16889ffa.png)
