### ISSUE TITLE
Implement new objects and methods by @apss-fuchs

### ISSUE THREAD

**Issue by scorninpc** [scorninpc/php-gtk3#28]
- TreeViewColumnSizing
- GtkTreeView->columns_autosize
- GtkTreeView->set_headers_visible
- GtkTreeViewColumn->set_max_width
- GtkTreeViewColumn->set_cell_data_func
- GtkEventBox
- GtkSeparator
- GtkTreeSortable (interface)
- GtkTreeModelSort (interface)

Thanks @apss-fuchs

**Comment by scorninpc** [comment]
- TreeViewColumnSizing
```
GtkTreeViewColumn::GROW_ONLY
GtkTreeViewColumn::AUTOSIZE
GtkTreeViewColumn::FIXED
```

- GtkTreeView->columns_autosize
```
$tree->autosize();
```

- GtkTreeView->set_headers_visible
```
$tree->set_headers_visible(FALSE);
```

- GtkTreeViewColumn->set_max_width
```
$column2->set_max_width(100);
```

- GtkTreeViewColumn->set_cell_data_func
```
Cannot be replaced by edited signal emmited by cellrender when it is edited?
```

- GtkEventBox
```
$event = new GtkEventBox();
```

- GtkSeparator
```
$sep = new GtkSeparator();
```

- GtkTreeSortable (interface)
- GtkTreeModelSort (interface)
```
I need to create better way to inheritance like CPP, because PHP theren't way to do multiple inheritance
```

**Comment by apss-fuchs** [comment]
> #GtkTreeViewColumn->set_cell_data_func
> Cannot be replaced by edited signal emmited by cellrender when it is edited?
> 

What do you mean exactly?
Can find the function here: 
https://docs.gtk.org/gtk3/method.TreeViewColumn.set_cell_data_func.html

We need this to highlight certain row fields. (e.g change the background-color)

**Comment by scorninpc** [comment]
Ok, i think you are right, so i've implemented

![image](https://user-images.githubusercontent.com/2607849/213928375-c84dd1f8-38d5-48de-b9f2-79195f011a4e.png)

https://github.com/scorninpc/php-gtk3/blob/master/examples/test8.php#L8

**Comment by scorninpc** [comment]
new methods to be added:

```
GtkLabel->set_line_wrap()
TreeSortable->set_sort_column_id();
TreeSortable->set_sort_func();
GtkButton->set_focus_on_click() (from GtkWidget)
```

**Comment by scorninpc** [comment]
i think this can be closed, as this methos are all implemented ok? but any problem, please reopen
