### ISSUE TITLE
set_sort_column not working if column has a set_sort_func

### ISSUE THREAD

**Issue by apss-pohl** [scorninpc/php-gtk3#34]
When having a Table and use “set_sort_column” to a column that is configured to be sorted by a custom function the code breaks.
It does enter the function correctly but when trying to access the value of the second iter (first iter return a valid value)  it breaks without any warning.

If I set the sort column to anything else and manually set sorting to that column using the function everything works fine.

The difference to the manual triggering of the sort function is that it gets triggered every time and as soon as there are more then 1 entries in the model.
I suspect that somehow the second iter is not working if there are only 2 entries in the model.

**Comment by scorninpc** [comment]
Sven (i think), i cannot reproduce the problem. look:

![image](https://user-images.githubusercontent.com/2607849/216798981-807245e7-0e4c-477e-bc95-f1171dccea84.png)

Look to my code:

```php
<?php

Gtk::init();

function GtkWindowDestroy($widget=NULL, $event=NULL)
{
	Gtk::main_quit();
}

$win = new GtkWindow();
$win->set_default_size(300, 200);
$win->connect("destroy", "GtkWindowDestroy");

$vbox = new GtkBox(GtkOrientation::VERTICAL);
$win->add($vbox);

// treeviiew
$treeview = new GtkTreeView();
$treeview->get_selection()->set_mode(GtkSelectionMode::MULTIPLE); // enable multiple selections
$scroll = new GtkScrolledWindow();
$scroll->add($treeview);
$vbox->pack_start($scroll, TRUE, TRUE);

	// columns
	$column1 = new GtkTreeViewColumn("Name", new GtkCellRendererText(), "text", 0);
	$column1->set_sort_column_id(0);
	$treeview->append_column($column1);

	$column2 = new GtkTreeViewColumn("Phone", new GtkCellRendererText(), "text", 1);
	$column2->set_sort_column_id(1);
	$treeview->append_column($column2);

	$column3 = new GtkTreeViewColumn("Genre", new GtkCellRendererText(), "text", 2);
	$column3->set_sort_column_id(2);
	$treeview->append_column($column3);

// model
$model = new GtkListStore(GObject::TYPE_STRING, GObject::TYPE_STRING, GObject::TYPE_STRING);
$treeview->set_model($model);

	$model->append(["Bruno", "+55 43 9 9282-2039", "M2"]);
	$model->append(["Natália", "+55 17 8273-0293", "F2"]);
	$model->append(["Maria", "+49 4190-8140", "F3"]);
	$model->append(["Sven", "+49 0291-2450", "M3"]);

	// 1 is the second column
	$model->set_sort_func(1, function($GtkTreeModel, $GtkTreeIterA, $GtkTreeIterB) {
		var_dump("OK");
	});
	$model->set_sort_column_id(1, GtkSortType::ASCENDING);
	

// button to get selected
$button = GtkButton::new_with_label("get selected");
$vbox->pack_start($button, TRUE, TRUE);
$button->connect("clicked", function($widget) use ($treeview, $model) {
	$selection = $treeview->get_selection()->get_selected_rows($model);
	foreach($selection as $select) {
		$iter = $model->get_iter($select);
		
		var_dump($model->get_value($iter, 0));
	}
});

$win->show_all();
Gtk::main();
```

1. I set every colum id
2. Added the sort function
3. set column id 1 (second column) as default sorted

maybe one think you need to understand:

https://github.com/scorninpc/php-gtk3/blob/master/src/Gtk/GtkListStore.cpp#L414

`GtkListStore::set_sort_func()` expect 2 parameters, column id and sort method. If you no pass sort method, for example, it will give garbage on `int int_order = parameters[1];`, and maybe do it crash

So, or you always pass all parameters, like NULL when you dont have this parameter, or when you code C, you need verify if this parameter are present

Every method on my project miss this verification, so you always need to pass every parameter, or eventualy it will crash

**Comment by apss-pohl** [comment]
Also breaks if data is reassigned later during operation

**Comment by scorninpc** [comment]
Yes, that's a problem with your code. Lets try to explain, but i think i dont have english for that hahaha


First, look that the crash occur inside sort function

![image](https://user-images.githubusercontent.com/2607849/217108684-57ebe586-d6fb-45df-88d7-11e05ca92872.png)

so it's not `$model->set_sort_func` or `$model->set_sort_column_id` problem

I think you dont understand models structure. Model are not the visible widget. Model are a storage widget. When you set sort colum, model doesn't need to be showed to order. So you are trying to order some think without records

![image](https://user-images.githubusercontent.com/2607849/217109742-91d48176-19d5-4a13-983b-d986683000f5.png)

As you set the colum id, every time you add a new record, this will be ordered again. So when you put the first record, this will try to order, and doesn't exists line 2 yet

i've found a simple solution for your problem, that is validate the iter and returno NULL if its not valid, look

![image](https://user-images.githubusercontent.com/2607849/217113434-eae1ee41-1938-4312-8c28-065df73c1225.png)

https://github.com/scorninpc/php-gtk3/blob/master/src/Gtk/GtkListStore.cpp#L397

**Comment by apss-pohl** [comment]
Thank you Bruno,
we will adjust our code.
I found a bug in your last commit on this topic, PR is ready:
https://github.com/scorninpc/php-gtk3/pull/43/commits/61fd51eb213d29a6949f2943233735d2a1928e50
