### ISSUE TITLE
GTK Critical when using GtkStack

### ISSUE THREAD

**Issue by apss-pohl** [scorninpc/php-gtk3#35]
It happens when assigning a view with 
https://docs.gtk.org/gtk3/method.Stack.add_named.html

When looking up the code I noticed that “add_with_properties” is not used directly from the PHP-GTK3 code base.
Only one occurrence here:
https://github.com/scorninpc/php-gtk3/blob/master/src/Gtk/GtkContainer.cpp#L40

But it doesn’t print the exception : “"GtkContainer_::add_with_properties not implemented")”

**Comment by scorninpc** [comment]
`add_with_properties` and `add_named` are diferent methods.

`add_named` are [implemented](https://github.com/scorninpc/php-gtk3/blob/b43a78cce8d8d86f4aa745c161a53d8794188b51/src/Gtk/GtkStack.cpp#L20) 

did you need add_with_properties implemented?

**Comment by apss-pohl** [comment]
We use "add_named" but when using it we get a critical 
```
Gtk-CRITICAL **: 13:20:18.197: gtk_container_add_with_properties: assertion '_gtk_widget_get_parent (widget) == NULL' failed
```
It seems that "add_with_properties" is used somehow internal.

**Comment by scorninpc** [comment]
this error are telling that the $widget asserted doesn't have a children

**Comment by apss-fuchs** [comment]
The critical is called if a container with the same name is added.
I think it can be closed
