### ISSUE TITLE
 GObject::TYPE_LONG returns false in selection

### ISSUE THREAD

**Issue by apss-pohl** [scorninpc/php-gtk3#40]
Given the following code:

```php
<?php

Gtk::init();

function GtkWindowDestroy($widget=NULL, $event=NULL)
{
	Gtk::main_quit();
}

$win = new GtkWindow();
$win->set_default_size(300, 200);
$win->connect("destroy", "GtkWindowDestroy");

$vbox = new GtkBox(GtkOrientation::VERTICAL);
$win->add($vbox);

// treeviiew
$treeview = new GtkTreeView();
$treeview->get_selection()->set_mode(GtkSelectionMode::MULTIPLE); // enable multiple selections
$scroll = new GtkScrolledWindow();
$scroll->add($treeview);
$vbox->pack_start($scroll, TRUE, TRUE);

	// columns
	$column1 = new GtkTreeViewColumn("Name", new GtkCellRendererText(), "text", 0);
	$column1->set_sort_column_id(0);
	$treeview->append_column($column1);

	$column2 = new GtkTreeViewColumn("Phone", new GtkCellRendererText(), "text", 1);
	$column2->set_sort_column_id(1);
	$treeview->append_column($column2);

	$column3 = new GtkTreeViewColumn("Genre", new GtkCellRendererText(), "text", 2);
	$column3->set_sort_column_id(2);
	$treeview->append_column($column3);

	$column4 = new GtkTreeViewColumn("Login", new GtkCellRendererText(), "text", 3);
	$column4->set_sort_column_id(3);
	$treeview->append_column($column4);

	$column5 = new GtkTreeViewColumn("LONG", new GtkCellRendererText(), "text", 4);
	$column5->set_sort_column_id(4);
	$treeview->append_column($column5);
// model
$model = new GtkListStore(GObject::TYPE_STRING, GObject::TYPE_STRING, GObject::TYPE_STRING, GObject::TYPE_STRING, GObject::TYPE_LONG);
$treeview->set_model($model);

	$model->append(["Bruno", "+55 43 9 9282-2039", "M2", "02.02.2023 11:11:11", 0]);
	$model->append(["Natália", "+55 17 8273-0293", "F2", "01.02.2023 11:11:11",1234567890]);
	$model->append(["Maria", "+49 4190-8140", "F3", "02.01.2023 11:11:11", 12345678901234]);
	$model->append(["Sven", "+49 0291-2450", "M3", "12.02.2023 11:11:11", 3]);

	// 1 is the second column
	$model->set_sort_func(3, 'sortDate');
	$model->set_sort_column_id(3, GtkSortType::ASCENDING);
	

// button to get selected
$button = GtkButton::new_with_label("get selected");
$vbox->pack_start($button, TRUE, TRUE);
$button->connect("clicked", function($widget) use ($treeview, $model) {
	$selection = $treeview->get_selection()->get_selected_rows($model);
	foreach($selection as $select) {
		$iter = $model->get_iter($select);
		
		var_dump($model->get_value($iter, 4));
	}
});

function sortDate($model, $iter1, $iter2)
{
	$item1 = $model->get_value($iter1, 3);
	$item2 = $model->get_value($iter2, 3);
	$val1  = strtotime(substr($item1, 0, 19));
	$val2  = strtotime(substr($item2, 0, 19));
	if ($val1 < $val2) {
		return -1;
	} elseif ($val1 == $val2) {
		return 0;
	} else {
		return 1;
	}
}

$win->show_all();
Gtk::main();
```
Returns false.  I added type LONG like this:
https://github.com/APS-Services/php-gtk3/blob/master/main.cpp#L4212

Maybe you spot the error?

**Comment by scorninpc** [comment]
Done dfc708babed02b60c0e1403b8a032fa302dc114f

**Comment by apss-pohl** [comment]
Unfortunately it doesn't work as expected yet:
![image](https://user-images.githubusercontent.com/95089598/217223261-24a530c3-f3fa-4ab1-b16b-69c7d31ba1a0.png)

And please revert back this typecast: Otherwise it breaks on windows build:
https://github.com/scorninpc/php-gtk3/pull/43/commits/8217d458d464b16f3304959ffda7efddba780834

**Comment by scorninpc** [comment]
I cannot reproduce it, maybe a windows problem?

![image](https://user-images.githubusercontent.com/2607849/217401310-cb2b32e9-21a1-479d-9af9-16e50ea3e060.png)

Look, when i set more than long value, its set to the max possible value

**Comment by scorninpc** [comment]
Maybe? 

![image](https://user-images.githubusercontent.com/2607849/217401495-d07cad3a-aaeb-4ea5-abad-8a39924eaf3d.png)

https://learn.microsoft.com/en-us/cpp/c-language/cpp-integer-limits?view=msvc-170

**Comment by apss-pohl** [comment]
We use "long long" in "phpgtk_get_gvalue" so in theory it should be fine.
Tried a lot around compile options and casting but i cant get it working on a windows build.

**Comment by scorninpc** [comment]
This is not from `phpgtk_get_gvalue`. I think you need to change here https://github.com/scorninpc/php-gtk3/blob/f1a243bb8a385fa9f55ceeb0e5a80ac1d08f9c1c/src/Gtk/GtkTreeModel.cpp#L84, no?

**Comment by apss-pohl** [comment]
Been there, tried e.g.: g_value_get_int64 but without any improvement.

https://github.com/APS-Services/php-gtk3/commit/9ad5f1d6b749e8381cfaee659d84ed9d15b85038#diff-f858f6a50e29bac657d97a796a7a0e7363bbfbae854e1fc50bb927d3aee57330L90

https://github.com/APS-Services/php-gtk3/commit/9ad5f1d6b749e8381cfaee659d84ed9d15b85038#diff-608d8de3fba954c50110b6d7386988f27295de845e9d7174e40095ba5efcf1bbL4297

**Comment by scorninpc** [comment]
Sorry, i cannot test

buy have you tried `return (long long)g_value_get_long(&value);` ?

**Comment by apss-pohl** [comment]
> try:
> 
> ```
> Php::call("var_dump", g_value_get_int64(&value));
> printf("%lld", g_value_get_int64(&value));
> return g_value_get_int64(&value);
> ```
Both already with wrong values. I can still see correct values inside teh append function, But from there it goes

> if both print correct, maybe is a PHP-CPP casting wrong. If only C++ way print correct, maybe PHP source cast problem
> 
> Anyway, take a look on Php::value conscturctors
> 
> https://github.com/CopernicaMarketingSoftware/PHP-CPP/blob/26cbf1e7b649062edb0786bc5df7b38d54123ff3/zend/value.cpp#L74.
I investigated there already. But i cant get where it is moving wrong.
I tried to implement a ulong type but this breaks during build.
https://github.com/CopernicaMarketingSoftware/PHP-CPP/commit/2a2e772e38ff3714bc90d43a765d0305829ab246

I was suspecting the compiler option "ZEND_ENABLE_ZVAL_LONG64" but no effect at all.

**Comment by apss-pohl** [comment]
We decided to go on using "string" :)

**Comment by apss-pohl** [comment]
Yes lets close. We also figured out: In PHP-GTK2 it was the same..
