### ISSUE TITLE
long long not compile on linux

### ISSUE THREAD

**Issue by scorninpc** [scorninpc/php-gtk3#46]
@apss-pohl this compile on Windows?

https://github.com/scorninpc/php-gtk3/pull/45/commits/96b1f04d9b29e18417c14d389c8c39336b11e9c7#diff-608d8de3fba954c50110b6d7386988f27295de845e9d7174e40095ba5efcf1bb

```cpp
long long b = (long long)phpgtk_value;
```

I got on linux

```
main.cpp:4132:34: error: conversion from ‘Php::Value’ to ‘long long int’ is ambiguous
         long long b = (long long)phpgtk_value;
```

Thats make sense that's not compile, as there is no `Php::Value` for `long long`

https://github.com/CopernicaMarketingSoftware/PHP-CPP/blob/master/zend/value.cpp#L54

As `int64_t` is a `long long` on Windows, I think we need stop to use `long long` and use only `int64_t` for compatibility

**Comment by apss-pohl** [comment]
On windows it`s just the other way round. 
![image](https://user-images.githubusercontent.com/95089598/218258949-18148768-8e09-4308-a396-d93f0e6e38f7.png)
"int64_t" is perfect!

**Comment by scorninpc** [comment]
ok, so i'll fix changing to int64_t ok?
