### ISSUE TITLE
New Windows build and install doc

### ISSUE THREAD

**Issue by scorninpc** [scorninpc/php-gtk3#47]
I wrote a new page with windows install and/or build page

https://github.com/scorninpc/php-gtk3/blob/master/docs/compile-windows1.md

I'll replace the next week if it's ok for all

**Comment by apss-pohl** [comment]
Hi @scorninpc ,
i just tried to build but i fail like this:
![image](https://user-images.githubusercontent.com/95089598/219029320-eb8b53f6-0478-4ed0-a136-91b8c5301488.png)

Any ideas?

**Comment by scorninpc** [comment]
Yes, i've this problem too. As `info->type` is `zend_type`, remove the cast. I think this is my workaround, but i only can confirm at night

Try remove to see what happen

**Comment by apss-pohl** [comment]
I think i missed something..
![image](https://user-images.githubusercontent.com/95089598/219031118-84d42bf5-1c34-4f2d-9dce-41cc3591a0ff.png)

**Comment by scorninpc** [comment]
Did you changed C compiler version too? you need change C++ to 17, also C to 17 too

**Comment by apss-pohl** [comment]
![image](https://user-images.githubusercontent.com/95089598/219040135-b792a303-5c66-4a40-a92f-7708cf23a067.png)
![image](https://user-images.githubusercontent.com/95089598/219040209-31c4329f-5bb9-4038-bc9b-361326cac3d3.png)

**Comment by scorninpc** [comment]
So I dont know, i'm not a noblesse at windows =/

Maybe something wrong on doc, or maybe some path os version you config wrong

**Comment by apss-pohl** [comment]
I could not find the time yet to retest. Maybe merge your changes but keep the old ones in a "old" file for comparison?

**Comment by scorninpc** [comment]
send me a email please, reminding me to send you my php-cpp changes. i'll zip and send to you. what do you think? this way we can see if your problem is php-cpp or some config

**Comment by scorninpc** [comment]
This is my [PHP-CPP-master.zip](https://github.com/scorninpc/php-gtk3/files/10772686/PHP-CPP-master.zip)

**Comment by apss-pohl** [comment]
This was working now with a minor fixe:
https://github.com/scorninpc/php-gtk3/pull/52/commits/4e2735afa1228c3b9295ac2ee00a14497c5f3f7e
I added your changes into this repo i was already using in the branch fork:
https://github.com/apss-pohl/PHP-CPP-win/tree/fork

I could build 8.1 & 8.2
