### ISSUE TITLE
GtkComboBox 'scroll_event' breaks

### ISSUE THREAD

**Issue by apss-pohl** [scorninpc/php-gtk3#49]
We want to prevent scrolling inside a combobox. When we listen to the event it breaks.
Here is a reproduction code.

```php
<?php
function disableScroll($widget, $event)
{
	$widget->emit_stop_by_name("scroll-event");
	return false;
}

Gtk::init();

defined("APPLICATION_PATH") || define("APPLICATION_PATH", dirname(__FILE__));

$field = new GtkComboBox();
$store = new GtkListStore(GObject::TYPE_STRING, GObject::TYPE_STRING);
$renderer    = new GtkCellRendererText();

foreach (['Test1','Test2','Test3','Test4','Test5','Test6','Test7','Test8',] as $key => $entry) {
	$store->append(array($key, $entry));
}
$field->set_model($store);

$field->pack_start($renderer, false, false, 0);
$field->add_attribute($renderer, 'text', 1);
$field->set_size_request(-1, 30);

// Testcode
$field->connect('scroll_event', function () {var_dump(2222);return true;});

// Target GTK2 CODE
// $field->connect('scroll_event', function ($widget, $event) {
// 	$widget->emit_stop_by_name("scroll-event");
// 	return false;
// });

// Window
$window = new GtkWindow();
$window->connect("destroy", function() {
	Gtk::main_quit();
});
$window->add($field);
$window->set_default_size(300, 200);
$window->show_all();

Gtk::main();
```

**Comment by scorninpc** [comment]
Probably you need to add mas `GDK_SCROLL_MASK` to `GdkWindow`, as the doc say https://docs.gtk.org/gtk3/signal.Widget.scroll-event.html

I've added the method on `GtkWidget`, not on `GObject` https://github.com/scorninpc/php-gtk3/blob/f1a243bb8a385fa9f55ceeb0e5a80ac1d08f9c1c/src/Gtk/GtkWidget.cpp#L497

So i cannot add this event to Gdk objects

I'll try this at night and see if segmentation stops

**Comment by scorninpc** [comment]
Ok i found the problem

Sometimes GdkEventKey doesn't have [string](https://docs.gtk.org/gdk3/struct.EventKey.html) property, and this is causing this segmentation fault

fixed https://github.com/scorninpc/php-gtk3/commit/f350d7c4c84ca30c9f8de5dfece2734627b091b6
