### ISSUE TITLE
Warnings with new build

### ISSUE THREAD

**Issue by apss-pohl** [scorninpc/php-gtk3#53]
Hi,

your last change causes a bunch of warnings. Here some information that might help you.
![image](https://user-images.githubusercontent.com/95089598/220058640-33cdbac5-4351-46ce-a309-0c011cac7d8d.png)

**Comment by scorninpc** [comment]
Ok, i found the problem, but you need to know, only GtkTextTag and GtkCellRendererText has property `foreground`

![image](https://user-images.githubusercontent.com/2607849/220174216-5dd41a89-a356-4d07-ab01-2b1eac0d0313.png)

now when its fail, will return false, not break anymore bfad9b9d007e2ec9cac10d6512da10c60f7b37f5

**Comment by apss-pohl** [comment]
Now it breaks on a different part:
```php
            $cell_renderer = new GtkCellRendererText();
            $cell_renderer->set_property('font', 'Arial Bold ' );
```
But property should exist:
https://docs.gtk.org/gtk4/class.CellRendererText.html

**Comment by scorninpc** [comment]
This is inside `set_cell_data_func`?

if i comment all about set_property, segment fault still occur

![image](https://user-images.githubusercontent.com/2607849/220366950-cb2336d5-055b-49c0-9395-1c189f623367.png)

I'm investigating `GtkTreeViewColumn_::set_cell_data_func`

**Comment by apss-pohl** [comment]
No, this happens in a "normal" context.

**Comment by scorninpc** [comment]
o do some changes, please, confirm if this is working https://github.com/scorninpc/php-gtk3/commit/ebd7d7e7cc02a93565d75557b3c88fa752dd4dc8

```php
<?php

/**
 * PHP-GTK Cookbook
 * 
 * https://andor.com.br/php-gtk/cook/how-to-set-format-in-gtktreeview
 */

Gtk::init();

$window = new \GtkWindow();
$window->set_size_request(500, 500);
$window->set_title("PHP-GTK");

// create a box
$vbox = new \GtkBox(GtkOrientation::VERTICAL);
$vbox->set_border_width(10);

// create the treeview, added it inside a scrolled window, and pack scrolled windows to box
$treeview = new GtkTreeView();
$scroll = new GtkScrolledWindow();
$scroll->add($treeview);
$vbox->pack_start($scroll, TRUE, TRUE, 0);

	// columns
	$column1 = new GtkTreeViewColumn("#", new GtkCellRendererText(), "text", 0);
	$treeview->append_column($column1);

	// columns
	$column2 = new GtkTreeViewColumn("Name", new GtkCellRendererText(), "text", 1);
	$treeview->append_column($column2);

	// value
	$column3 = new GtkTreeViewColumn("Value", $renderer = new GtkCellRendererText(), "text", 2);
	$treeview->append_column($column3);
	$renderer->set_property("font", "Arial Bold");
	$column3->set_cell_data_func($renderer, function($column=NULL, $renderer=NULL, $model=NULL, $iter=NULL, $a=NULL, $b=NULL, $c=NULL) {

		// get value of column
		$value = $model->get_value($iter, 2);
		
		// format
		$renderer->set_property("text", "$" . $value);
		$renderer->set_property('cell-background', "yellow");
	});

// create model
$model = new GtkListStore(GObject::TYPE_INT, GObject::TYPE_STRING, GObject::TYPE_DOUBLE);
$treeview->set_model($model);

// add some values
$model->append([1, "scorninpc", 30]);
$model->append([2, "admin", 28.18]);
$model->append([3, "bruno", "92.82"]);


// add to window
$window->add($vbox);

// connect to signal that close program
$window->connect("destroy", function() {
	Gtk::main_quit();
});

// show all and start
$window->show_all();
Gtk::main();

die();
```

**Comment by apss-pohl** [comment]
Working now, thank you!

FYI: Your last commit breaks the build:
https://github.com/scorninpc/php-gtk3/commit/2117d6c6f53ce8230ae2b12578f34737d495e276

![image](https://user-images.githubusercontent.com/95089598/220563483-a2239f11-b344-4f44-bb28-a472f0bf1340.png)

**Comment by apss-pohl** [comment]
I want to do, but github always merges the PR`s :(
Maybe i am doing something wrong there
