### ISSUE TITLE
Backgrounds transparent

### ISSUE THREAD

**Issue by apss-pohl** [scorninpc/php-gtk3#58]
Hi Bruno,

since your last commit`s many of the backgrounds got transparent. Lists or entries are not affected.I could not figure out yet why this is exactly.
This is what it looks like, the tiny grey line on the left middle is the end of the GTK window.
![image](https://user-images.githubusercontent.com/95089598/221900082-e98fc134-ef6f-472b-85fd-6e39ca9d89a2.png)

**Comment by scorninpc** [comment]
Very stranger! I not changed nothing, only new things!

Can you provide a minimal source code with example?

Thanks

**Comment by apss-pohl** [comment]
We figured some stuff out. In GTK2 we used code like this:
```php
$alert_win->override_background_color(GtkStateFlags::NORMAL, GdkRGBA::parse('#ffbebf'));
```
This is wrong code and in our testfile it breaks with a critical complaining that the second param is not a string.
![image](https://user-images.githubusercontent.com/95089598/222369647-3a882f3a-6818-4cc1-acb0-6b1e2bd7e1d8.png)


However in our codebase it doesn't break and we have those transparent windows.

Changing to 
```php
$backgroundColor = GdkRGBA::parse('#ffbebf');
$alert_win->override_background_color(GtkStateFlags::NORMAL, $backgroundColor->to_string());
```
It works as expected.

**Comment by scorninpc** [comment]
Sorry for that: i parse the string inside the `override_background_color` https://github.com/scorninpc/php-gtk3/blob/6784766e27a9618e1686ef0e3b0fd7a0eb1bad50/src/Gtk/GtkWidget.cpp#L827

I'll change this. Anyway, I think this is not the cause of transparency, but i'll change it to test

**Comment by apss-pohl** [comment]
It seems to be a strange race condition with the rest of the code. I cant reproduce it outside our main app. 
We migrated the code now so it`s ok already.

**Comment by scorninpc** [comment]
Fixed the parameter. Now you can pass a string or GdkRGBA

```php
$label->override_background_color(GtkStateType::NORMAL, "rgba(150, 0, 0, 0.5)");
```

or 
```php
$label->override_background_color(GtkStateType::NORMAL, GdkRGBA::parse("#FF0000"));
```

**Comment by apss-pohl** [comment]
Thank you!
