### ISSUE TITLE
GdkThreads

### ISSUE THREAD

**Issue by apss-pohl** [scorninpc/php-gtk3#62]
Hi Bruno,
would you consider to implement GdkThreads?
https://gitlab.gnome.org/rmader/gtk/-/blob/composite-templates/gdk/gdkthreads.h

**Comment by scorninpc** [comment]
There is no documentation for that, this is a oficial implementation? is a exposed object?

https://docs.gtk.org/gdk3/enum.InputSource.html?q=GdkThreads
https://docs.gtk.org/gdk4/enum.InputSource.html?q=GdkThreads

What do you want to do?

**Comment by apss-pohl** [comment]
I´d like to refactor some of our code following this example for improve performance:

https://stackoverflow.com/a/30613369
https://docs.gtk.org/glib/func.idle_add.html

**Comment by scorninpc** [comment]
ah i got!

You can do that with https://github.com/scorninpc/php-gtk3/blob/master/src/Gtk/Gtk.cpp#L37
