### ISSUE TITLE
set/get_data

### ISSUE THREAD

**Issue by apss-pohl** [scorninpc/php-gtk3#63]
Hi Bruno,

i need to add 
https://docs.gtk.org/gobject/method.Object.get_data.html
https://docs.gtk.org/gobject/method.Object.set_data.html

my code so far:

```c++
Php::Value GObject_::get_data(Php::Parameters& parameters)
{
    std::string s_key = parameters[0];
    gchar* key = (gchar*)s_key.c_str();

    gpointer value = g_object_get_data(G_OBJECT(instance), key);

    return (char)value;
}


void GObject_::set_data(Php::Parameters& parameters)
{
    std::string s_key = parameters[0];
    gchar* key = (gchar*)s_key.c_str();

    std::string s_value = parameters[1];
    gpointer* value = (gpointer*)s_value.c_str();

    printf("%p", value);

    g_object_set_data(G_OBJECT(instance), key, value);
}
```

What i get right now:
```sh
string(11) "get_data: �"
string(11) "get_data: \000"
```

I think the set_data is ok, but the get data doesn't return a string but a pointer right now. I am struggeling with the type conversion. Its somesint very silly i guess but i cant find it, can you point me to the right direction?

Thank you,
Sven

**Comment by scorninpc** [comment]
i dont remenber to use this sometime. I always used a extended class and use this values on PHP class.

Anyway, i'll see how implement this. This store only strings?
