### ISSUE TITLE
glade files

### ISSUE THREAD

**Issue by subabrain** [scorninpc/php-gtk3#67]
Hello together and happy easter,

after a long time i have to say something ...

you have to integrate this file ("gschemas.compiled") into the windows version in folder "\share\glib-2.0\schemas":

[gschemas.compiled.txt](https://github.com/scorninpc/php-gtk3/files/11189982/gschemas.compiled.txt)

just remove the .txt extension and put it in:

<phpgtk_folder>\share\glib-2.0\schemas\

And one other thing ...

i cant get glade files to run with your windows build ... maybe you can check this ;)

ok - thats all :)

Have a good time!

Greets
Robert

**Comment by scorninpc** [comment]
Hello Robert, how are you?

I missed gshemas in the some point, my bad!

I'll try to run on windows and do some testes with Glade. Can you provide more details about the error and the files that you try to run?

Thanks

**Comment by subabrain** [comment]
Hi Bruno,

im fine - thx! I hope you are fine too?

yes the problem is he cant find the gladexml class:

Fatal error: Uncaught Error: Class "GladeXML" not found in C:\PHP-GTK\..."

maybe someone can have a look at this ... i will also have a look at it :)

So - all the best!

Greets
Robert

**Comment by scorninpc** [comment]
Hey Robert

GladeXML doesn't exists anymore. Gtk and Glade use the same support of GtkBuilder, and doesn't run as plugin/extension

![image](https://user-images.githubusercontent.com/2607849/231303910-5f0c4cc4-fe91-43ac-91d9-4fd614c5f2df.png)

**Comment by subabrain** [comment]
Hi,

ah ok - i see - thx a lot!

Greets
Robert

**Comment by scorninpc** [comment]
i'll close, but anything just reopen
