### ISSUE TITLE
change cursor

### ISSUE THREAD

**Issue by subabrain** [scorninpc/php-gtk3#71]
Hello,

i have a simple question :P 

i tried to make a new cursor with the following code:

        $this->window = $this->builder->get_object("window");

        ...

        $ctype = new GdkCursorType("GDK_X_CURSOR");
        $cursor = new GdkCursor($ctype);
        $this->window->set_cursor($cursor);

but it crashes - maybe someone could help here - thx a lot!

Edit: but i cant find this class in the phpgtk3 sourcecode ...

Greets
Robert

**Comment by scorninpc** [comment]
Hey Robert, how is going?

`gtk_widget_set_cursor` is a Gtk4 method. For Gtk3 we use `gdk_window_set_cursor`. BTW is not implemented.

I'll implement it for you tomorow ok?

**Comment by scorninpc** [comment]
Hello Robert,

I've implemented the cursor change, look:

![image](https://user-images.githubusercontent.com/2607849/235933579-48881531-4c76-4fc5-a0d2-9b5fa0328b8d.png)

```php
<?php

Gtk::init();

// create the window
$window = new GtkWindow();
$window->set_size_request(300, 200);
$window->set_name("mywindow");

// create a box
$vbox = new \GtkBox(GtkOrientation::VERTICAL);
$vbox->pack_start($a = new GtkLabel("My Window"), TRUE, TRUE);
$a->set_name("button1");

// connect to destroy
$window->connect("destroy", function($window) {
	Gtk::main_quit();
});


// add widget
$window->add($vbox);

// run
$window->show_all();

// change cursor (the window exists only after show)
$cursor = new GdkCursor(GdkCursorType::X_CURSOR);
$window->get_window()->set_cursor($cursor);

// loop
Gtk::main();
```

If you can, pull the repository and compile. If no, i'll create a new release in the next week

Thanks

**Comment by subabrain** [comment]
Hello Bruno,

im fine - thx! I hope your doing well?

Thanks a lot for your Implementation and Help!

I will give a try :)

Thx and Greets!
Robert

**Comment by subabrain** [comment]
Ah by the way (off topic) but i will try to modify my RPGET for also encrypt .ui / glade files - i will inform you if its ready :)

Greets
Robert
