### ISSUE TITLE
Is it's possible to GtkListBoxRow->get_index?

### ISSUE THREAD

**Issue by ntfs1984** [scorninpc/php-gtk3#73]
Hello.

Did not found how to determine which row was selected on GtkListBox.

```
<?php
$listbox = new GtkListBox();
$listbox->insert(some_thing, 1);
$listbox->insert(some_thing1, 2);
$listbox->insert(some_thing1, 3);
$listbox->connect("row-activated", function() {some_function();});

function some_function(){
$listboxrow = new GtkListBoxRow();
$z = $listboxrow->get_index($listbox->get_selected_row()); // This is I think, how it should be
echo "Index: ".$z;
}
```

As I saw, GtkListBoxRow implementation doesn't have method "get_index". So my question: is it possible to implement this method or something like that ?

**Comment by scorninpc** [comment]
Hey, hello.

First, thank you for sponsorship

Why just not get it from signal callback?

```php
<?php

	Gtk::init();

	// create the window
	$window = new GtkWindow();
	$window->set_size_request(300, 200);

	$listbox = new GtkListBox();
	$listbox->insert(new GtkLabel("ITEM 1"), 0);
	$listbox->insert(new GtkLabel("ITEM 2"), 1);
	$listbox->insert(new GtkLabel("ITEM 3"), 2);

	$listbox->connect("row-activated", function($listbox, $row) {
		
		var_dump($row);
		var_dump($row->get_child());

	});

	$window->add($listbox);
	$window->show_all();

	Gtk::main();
```

![image](https://github.com/scorninpc/php-gtk3/assets/2607849/821cfafa-b39b-4100-a326-ccd241deb054)

**Comment by ntfs1984** [comment]
Yeah, your easy solution is better.

Method is here: https://docs.gtk.org/gtk3/method.ListBoxRow.get_index.html - it's not a ListBox, but ListBoxRow - it returns index of selected element.

Anyway, I think we can close issue.

Thanks for quick respond and help.
