### ISSUE TITLE
Method "connect" leaks memory OR method "destroy" doesn't destroy all children

### ISSUE THREAD

**Issue by ntfs1984** [scorninpc/php-gtk3#81]
Hello. Found that "connect" method leaks memory if applied to previously declared and even destroyed object.

Example.
```php
<?php
Gtk::init();
function GtkWindowDestroy($widget=NULL, $event=NULL)
 {
 Gtk::main_quit();
 }

function refresh() 
 {
 global $win, $box, $button;
 $box->destroy();
 $button->destroy();	
 $box = new GtkBox(GtkOrientation::HORIZONTAL);
 $button = GtkButton::new_with_label(rand(1,100));
 $button->connect("clicked",function($button) {}); // Comment this to stop memory leak
 $box->add($button);
 $win->add($box);	
 $button->show();
 $box->show();
 echo "\n".round(memory_get_usage()/1024,2) . " Kb\n";
 } 

$win = new GtkWindow();
$win->set_default_size(300, 200);
$win->connect("destroy", "GtkWindowDestroy");
$box = new GtkBox(GtkOrientation::HORIZONTAL);
$button = GtkButton::new_with_label(rand(1,100));
$box->add($button);
$win->add($box);
Gtk::timeout_add(2000, function () {refresh();return true;});
$win->show_all();
Gtk::main();
```

This code leaks memory upon every iteration of timeout_add.
If we comment line "$button->connect("clicked",function($button) {});" - memory stopped to leak, this means that g_signal_connect doesn't replace function within previously declared object, but add it. 

Is there a way to fix such situation according example?
Thanks.

**Comment by scorninpc** [comment]
Hey Hello!

As you can see [on doc](https://docs.gtk.org/gtk3/vfunc.Widget.destroy.html), destroy not free memory

```
widget will still point to valid memory, allowing you to release the references you hold, but you may not query the widget’s own state. ```

Look a nice [reference](https://stackoverflow.com/a/17734500/1935882) too

Manage memory on GTK is not a simple task, as well the problem of clone objects

If you want a deep understand of Gtk memory, this a [famous article ](https://www.cs.hunter.cuny.edu/~sweiss/course_materials/csci493.70/lecture_notes/GTK_memory_mngmt.pdf)

In any case, I dont see any use of recreate all stack of widgets every 2 seconds, as we can se global variables or so! This cause not only memory problem, but use of cpu and disk also

**Comment by ntfs1984** [comment]
I'm still checking all possible solutions to create system tray for your dock. 

I found way to do this over d-bus.

Any change of system tray state (for example incoming message to messenger) requires re-draw of system tray (like it used in X system tray apps) with new properties of applications.

So, recreation of stack performing not at every 2 sec, but at every changed state. Received message to Telegram - icon recreated, +2Kb of memory used. Have read message of Telegram - icon recreated, +2Kb of memory used.

But thanks for links, will dig how to resolve these memory leaks.

**Comment by scorninpc** [comment]
if you do successfully icon tray, i'd like to take a look and add this to cookbook. I know this is a UX features of all OS (windows, linux, mac) but I love systray too

**Comment by ntfs1984** [comment]
Well, if shortly:
 - There is exists utility called "snixembed". It's proxying old xembed calls to modern SNI to d-bus
 - After run this utility in background, all new apps who using system tray - will create new D-bus service StatusNotifierItem.
 - In this service are methods and properties for: a) get current icon to display it; b) title and tooltip; c) method which we might simply call and application will activate or display context menu.

I'm not professional programmer, so not able to see all best methods, but you can use this snixembed app and d-feet utility to understand how it works.

**Comment by scorninpc** [comment]
ahhh very nice workaround!

**Comment by ntfs1984** [comment]
Anyway want to re-open ticket just for your info.
Step by step I found root of memory leak, and it's GTK.

Function "**Php::Value GObject_::connect_internal**" of GObject.cpp contains some struct called "**callback_object**".
This struct seems is not freeing before end of function.

It's not a critical bug, but you will 100% meet it once will develop some software with content refresh and big uptime, like dockStupido.

**Comment by scorninpc** [comment]
Oh! nice to know! I'll investigate if we can free this to prevent it. Thank you for report

**Comment by ntfs1984** [comment]
Added callback_object to public field of class to make it visible outside. Not sure how to explain this correctly.

**GObject.h**:
```cpp
        public:
struct st_callback;
st_callback *callback_object;
```

Then added deletion of this var into handler_disconnect function.

**GObject.cpp**:
```cpp
void GObject_::handler_disconnect(Php::Parameters &parameters)
{
    Php::Value callback_handle = parameters[0];
    delete callback_object;
    g_signal_handler_disconnect(instance, (int)callback_handle);
}
```
So now we can run handler_disconnect when necessary and it will also release memory used by struct. 
Tested, this works, so you can get this idea.

**Comment by scorninpc** [comment]
Ok, i got, but if you disconnect before reconnect your self with PHP, without delete, still leaking memory?

Because what are telling make sense, but all structures on callback_object are primitive like or small classes. it's free some bytes only

I'll update with this code, because make sense free the object, but it's not will leak so many memory

**Comment by ntfs1984** [comment]
Yes, it's not leaking so many memory, just about 1Kb for iteration.
But if we have many iterations - this leak is sensitive.

If we'll refresh every 250ms - our program will eat + 1Mb every 4.5 min, or + 1Gb every 3 days. It's so much. 
You can check with my initial example.

**Comment by apss-pohl** [comment]
I compiled for windows, now i get a lot of those:

```sh
(php.exe :4948): GLib-GObject-CRITICAL **: 09:24:38.068: g_object_weak_unref: couldn't find weak ref 00007ffbe68f7e90(0000026b7388c0f0)
```

**Comment by apss-pohl** [comment]
mingw-w64-x86_64-gtk3 3.24.39-1
mingw-w64-x86_64-glib2 2.78.3-1
mingw-w64-x86_64-pango 1.50.14-4

Versions are stable, once i revert the changes the error disappears using same environment.

**Comment by scorninpc** [comment]
Yes, the reverted version does not have `g_object_weak_unref`. All i found on web tell this is a glib related

![image](https://github.com/scorninpc/php-gtk3/assets/2607849/7d53f9b8-ef33-427f-b006-c9ec1ba70fe5)


Can you upgrade glib to `2.80`? yours is `2.78`

**Comment by scorninpc** [comment]
for real? i have 8.1 compiled here! 

I'll do another VM to make a new compile env, and try to do some tests

But i'm sure that problem is part of GTK/Glib/Pando problem, not PHP-GTK it's self

Maybe try clear structure by another way to avoid this bug, but ... need tests

**Comment by scorninpc** [comment]
Did you try update only on mingw?

![image](https://github.com/scorninpc/php-gtk3/assets/2607849/2635b648-f673-4b8a-bb49-bcd16e4d682f)

**Comment by apss-pohl** [comment]
I updated all dependencies und rebuild php and gtk3 on top of this. But the error persists

**Comment by apss-pohl** [comment]
Yes i tried this and the version is "mingw-w64-x86_64-glib2-2.80.0-1"

I also updated the build depedencies for php itself against the lastest versions from msys and rebuild it +gtk3 on top of it. But the issue persists..

**Comment by scorninpc** [comment]
sad to hear that! i think i'll try to avoid `g_object_weak_unref` method

**Comment by apss-pohl** [comment]
Just tried it but i don't see anything changed. What to expect? IF you are online we can also chat on discord for testing

**Comment by ntfs1984** [comment]
Just tested. Works fine without any tricks, thanks.

@apss-pohl - tested with php8.1 on archlinux - running without problems.

**Comment by apss-pohl** [comment]
Hi Bruno,

do you consider to revert that change? 
g_object_weak_unref still causes the issues

**Comment by scorninpc** [comment]
Hey, how are you!

Yes, i'm waiting you confirm if I can revert

**Comment by apss-pohl** [comment]
Well i am using it without the "g_object_remove_weak_pointer" all the time very intensive, i don't have any issues. Here is a PR:
https://github.com/scorninpc/php-gtk3/pull/132

**Comment by scorninpc** [comment]
Ah ok! Very nice

But i think you can remove this PR, because there is more thing to remove https://github.com/scorninpc/php-gtk3/commit/d176b1472bbb2757cf56fbe383bb808cbcf06369 and revert is more easy

**Comment by apss-pohl** [comment]
Whatever fits best for you. I only did this one liner and it seems fine, but i also have no clue what the other stuff will do

**Comment by scorninpc** [comment]
fixed https://github.com/scorninpc/php-gtk3/commit/09e9cdec470c1fef8682133baa013c447cc8e753

i just comment methods, becase i loved to find that to just remove it now hahah
