### ISSUE TITLE
Heed help with build documentation

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#85]
Could somebody please tell me what exactly to change, according to this [documentation](https://github.com/scorninpc/php-gtk3/blob/master/docs/compile-linux.md#compile-php-cpp-from-source):
> Edit PHP-CPP/Makefile to use /opt/php/php-8.1.14/bin/php-config.

p.s. Discussions feature enabled would be good option for Q&A here.

**Comment by scorninpc** [comment]
Hello [d47081](https://github.com/d47081)

You need php-config to run some auto-configs. `php-config`  is part of `php-dev` package

If you want to compile with php system version, just use `php-config` without path, or run `which php-config` to find location

If you cannot find php-config, you may need to install `php-dev` package or use appimage provided on release page 

> p.s. Discussions feature enabled would be good option for Q&A here.

The communit is small yet, maybe some day
