### ISSUE TITLE
How to make async Label update?

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#87]
I'm experimenting [here](https://github.com/YGGverse/Yoda/blob/main/src/Box/Main.php#L77) with browser app for Gemini protocol, and can't update GtkLabel text twice on `activate` event.

I want to write `Loading...` text in Label tray before page complete to load then update this label by `Loading completed` text.

By the fact, script uses last construction  that overwrites first one 

```
$this->tray->label->set_text('Loading...');
// ...request delay
$this->tray->label->set_text('Loading completed');
```

Is any ideas about multi-thread / async or maybe GTK solution for PHP?

**Comment by scorninpc** [comment]
PHP cannot do async actions without extensions. Maybe you need to install `Swoole`. This will work like a charm

If you dont want to install that, maybe you need verify every 1 sec for example

```php
Gtk::timeout_add(250, function () {
	$this->tray->label->set_text('Loading...');
	// ...request delay
	$this->tray->label->set_text('Loading completed');
});
```
