### ISSUE TITLE
Optimal GTK container for long text in GtkScrolledWindow

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#88]
Currently, I'm using GtkLabel to output HTML text of webpage in my browser.
Is this good idea or maybe some alternative container type available for these needs?

Maybe my question about GTK mostly, but this library makes me inspired to first steps. 

Thanks for your work!

**Comment by scorninpc** [comment]
I dont know what are you doing with this html. But if GtkLabel are working ... ok

I really dont know about what `markup` can do or complexity of your html

**Comment by scorninpc** [comment]
No, GtkLabel is not limited by chars count. Is used to display text, not small text. You can use this, and I don't know any other widget to just display text on GTK
