### ISSUE TITLE
Can't open the link defined in GtkLabel tag

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#89]
According to this example
https://andor.com.br/php-gtk/cook/how-to-put-link-inside-gtklabel

On click the link:
> Firefox is already running, but is not responding. To use Firefox, you must first close the existing Firefox process, restart your device, or use a different profile.

Is there any build-in functions for example to open links in the new tab?

i3 / Debian

**Comment by scorninpc** [comment]
I dont get you problem, sorry. I think you dont understand how signals work

All widget has `button-press` signal, for [example](https://docs.gtk.org/gtk3/signal.Widget.button-press-event.html)
