### ISSUE TITLE
Undefined method GtkScrolledWindow::set_max_content_width

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#91]
``` php
$scroll = new \GtkScrolledWindow();
$scroll->set_max_content_width(100);
```

is `set_max_content_width` implemented?

**Comment by scorninpc** [comment]
No, you can try set propertie `max-content-width`

https://docs.gtk.org/gtk3/method.ScrolledWindow.set_max_content_width.html

**Comment by scorninpc** [comment]
Done https://github.com/scorninpc/php-gtk3/commit/c5fbf1b04c72797e7795d38887cc32da3ee958a8
