### ISSUE TITLE
GtkTreeView & row-activated attribute issue

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk3#97]
I don't understand why second argument of `row-activated` event is `GdkEvent`, not `GtkTreePath` as [documented](https://docs.gtk.org/gtk3/signal.TreeView.row-activated.html)

Could somebody check? 

Example:

``` php
$treeview = new \GtkTreeView();
...
$treeview->connect(
    'row-activated',
    function (
        $GtkTreeView, 
        $GdkEvent, // should be GtkTreePath not GdkEvent
        $GtkTreeViewColumn
    ) {
...
```

**Comment by scorninpc** [comment]
Sorry, i cannot answer this, as i don't manipulate signals or parameters. I just abstract ONE method to handle all signals in they original format. So, I don't know why

And i don't have been used row-activated and find little result of this to see how it's work

maybe a GTK bug when connect with closure? i don't know

I can help much more if you post code and what do you want to do

For example, you want to catch the clicked row? column? did you got by GtkTreeSelection?

```php

$treeview->connect("row-activated", function ($tree, $event, $column) {

		list($model, $iter) = $tree->get_selection()->get_selected();

		$value = $model->get_value($iter, 0);

		var_dump($value);

	});
```

**Comment by scorninpc** [comment]
this warnings is normal, depending what gtk version are you using for example. Themes can trigger alot warnings too. I'm planning a config to disable this warnings

ps: your interface is looking beautiful

**Comment by scorninpc** [comment]
> Suppose, that must to define GDK instance somewhere (I have no experience with this framework yet) - usually, similar errors happened when class operating with undefined entities

you can configure type of warning, to much detailed as PHP warnings
